# Generated by Django 3.1.4 on 2021-04-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='income',
            name='bookmark',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='bookmark',
        ),
        migrations.AlterField(
            model_name='expense',
            name='account',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Account', 'Account')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Going out/Fun', 'Going out/Fun'), ('Self-care', 'Self-care'), ('Transportation', 'Transportation'), ('Culture', 'Culture'), ('Household', 'Household'), ('Clothes', 'Clothes'), ('Beauty', 'Beauty'), ('Health', 'Health'), ('Education', 'Education'), ('Gift', 'Gift'), ('Tax', 'Tax'), ('Stocks', 'Stocks'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='account',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Account', 'Account')], max_length=100),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('Allowance', 'Allowance'), ('Salary', 'Salary'), ('Cash', 'Cash'), ('Bonus', 'Bonus'), ('Account', 'Through Account'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='From',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Account', 'Account')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='to',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Account', 'Account')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
